# Generated by Django 3.2 on 2021-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210816_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
