# Generated by Django 3.2 on 2021-08-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='task_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
