# Generated by Django 3.2 on 2021-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
