# Generated by Django 3.2 on 2021-08-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_task_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
