# Generated by Django 3.2 on 2021-08-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
    ]
