# Generated by Django 3.2 on 2021-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_task_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField()),
                ('task_ID', models.IntegerField()),
                ('complete', models.IntegerField(default=0)),
                ('repeat', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('user_ID', 'task_ID', 'date')},
            },
        ),
    ]
