# Generated by Django 3.2 on 2021-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='task_name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
